name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: spacemeowx2/devkitpro-action@latest
      with:
        cmd: make -j8

    - name: Upload built files
      uses: actions/upload-artifact@v1
      with:
        name: sdcard
        path: out/sd

    - name: Upload elf file
      uses: actions/upload-artifact@v1
      with:
        name: amz_mitm.elf
        path: amz_mitm/amz_mitm.elf
  